
version: '3.8'

services:
  probman:
    build:
      context: ..
      dockerfile: docker-judge/Dockerfile
    working_dir: /app/src/judge
    environment:
      - DATABASE_URL=${DATABASE_URL}  
    ports:
      - "8080:8080"

